create table usuario (
    id bigint not null generated by default as identity,
    nome varchar(100) not null,
    email varchar(100) not null unique,
    senha varchar(100) not null,
    perfis bigint not null,

    primary key(id),
    foreign key(perfis) references perfil(id) on delete cascade
);
