create table topico (
    id bigint not null generated by default as identity,
    titulo varchar(100) not null,
    mensagem TEXT NOT NULL,
    data_criacao timestamp not null,
    status varchar(20) not null,
    autor_id bigint not null,
    curso_id bigint not null,
    respostas bigint,

    primary key(id),
    foreign key(autor_id) references usuario(id),
    foreign key(curso_id) references curso(id)
);